### ISSUE TITLE
Ui is not proper when used it in landscape view

### ISSUE THREAD

**Issue by sevenbitsriddhi** [premkumarroyal/MonthAndYearPicker#3]
![screenshot_month_year_picker](https://user-images.githubusercontent.com/30856006/40720219-8f54fb54-6405-11e8-981b-487a75106220.png)

As you can see in the Image OK and Cancel button is not visible. when I tried to open the month picker in the landscape mode. (It is working fine with portrait mode)

**In portrait mode it looks like
![screenshot_month_year_portrait](https://user-images.githubusercontent.com/30856006/40720495-75de01ec-6406-11e8-927a-fcb788a36291.png)
:**

**Comment by premkumarroyal** [comment]
@sevenbitsriddhi  Please update to

`implementation 'com.whiteelephant:monthandyearpicker:1.2.1`

![screenshot_20180531-151046](https://user-images.githubusercontent.com/8821990/40793044-07cd031a-6519-11e8-9fc4-4f2624343280.png)

**Comment by sevenbitsriddhi** [comment]
thank you @premkumarroyal .
