### ISSUE TITLE
Positive Button and Negative Button 

### ISSUE THREAD

**Issue by jossshii** [premkumarroyal/MonthAndYearPicker#4]
Hi,

Excuse me, there's no 'setPositiveButton' and 'setNegativeButton' methods? So what's the purpose of this? how can I handle the choices made when hitting the 'OK' button?

Thank you

**Comment by premkumarroyal** [comment]
@jossshii 

While you are building the month and year picker, you need to pass `MonthPickerDialog.OnDateSetListener()` as a method parameter, this you can use as `setPositiveButton`. Once the user clicks on the `Ok` button you get notified. Currently, there is no public listener for `cancel`. 

Please find the example code : 

```
 MonthPickerDialog.Builder builder = new MonthPickerDialog.Builder(activity, new MonthPickerDialog.OnDateSetListener() {
                    @Override
                    public void onDateSet(int selectedMonth, int selectedYear) {
                      // Use this block to listen event once user click on OK button on MonthAndYearPicker
                    }
                }, today.get(Calendar.YEAR), today.get(Calendar.MONTH));
```

**Comment by jossshii** [comment]
Of course, how I couldn't realized! Thank you very much nice work.

**Comment by premkumarroyal** [comment]
Welcome :)

**Comment by demogorgorn** [comment]
Very good library! Thanks! I'll use it in my app

**Comment by premkumarroyal** [comment]
These appreciations motivate me to work on opensource projects. Thanks a lot :)
