### ISSUE TITLE
Picker is not localised

### ISSUE THREAD

**Issue by nikitagudkovs** [premkumarroyal/MonthAndYearPicker#5]
If run from non-english context picker still shows month names in English

**Comment by premkumarroyal** [comment]
@nikitagudkovs Please update version to 1.3.0. 

`compile 'com.whiteelephant:monthandyearpicker:1.2.1'`

Please find the below screen that is running is running in the Spanish context.

![screenshot_1536032600](https://user-images.githubusercontent.com/8821990/45008951-22439b00-b023-11e8-8e77-4f1ef79e6d6c.png)
