### ISSUE TITLE
How to get Month name ??

### ISSUE THREAD

**Issue by rohit6027** [premkumarroyal/MonthAndYearPicker#9]
I was trying to get month name. is there any way to get month name without using external code ??

**Comment by premkumarroyal** [comment]
Right now once the user selects the month and year you will get the month number (Range from 0 to 11). You can use Calendar class or DateFormatSymbols to get the month name.

Ex: 

Using Calender Class :

```
  SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MMMM", Locale.getDefault());
  Calendar calendar=Calendar.getInstance();
  calendar.set(Calendar.MONTH,selectedMonth);
  String selectedMonthName = simpleDateFormat.format(calendar.getTime());
  Log.d(TAG, "selected month name : "+selectedMonthName);
```

Using DateFormatSymbols : 

```
String[] _monthNames = new DateFormatSymbols(Locale.getDefault()).getMonths();
String selectedMonthName = _monthNames[selectedMonth];
Log.d(TAG, "selected month name : "+selectedMonthName);
```

**Comment by lazy-coder-10** [comment]
I do know this answer. I thought your library may give month name without
using that code.

Thanks for your reply. I have defined a static months array and based on
that no. I am picking month name from array.
